name: example
version: 1.0.0
homepage: https://github.com/Solido/Flutter-BlurHash
authors:
  - Robert Felker <flutter@robbieone.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_blurhash:
    path: ../

flutter:
  uses-material-design: true