name: example
version: 1.0.0
homepage: https://github.com/Solido/Flutter-BlurHash
authors:
  - Robert Felker <flutter@robbieone.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  inview_notifier_list: ^1.0.0
  google_fonts: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_blurhash:
    path: ../

flutter:
  uses-material-design: true