name: flutter_blurhash
description: Compact representation of a placeholder for an image. Encode a blurry image under 30 caracters for instant display like used by Medium
version: 0.2.0+1
homepage: https://github.com/fluttercommunity/flutter_blurhash
maintainer: Robert Felker (@Solido)

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^2.1.12
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
