name: flutter_blurhash
description: Compact representation of a placeholder for an image. Encode a blurry image under 30 caracters for instant display like used by Medium
version: 0.3.0
homepage: https://github.com/fluttercommunity/flutter_blurhash
maintainer: Robert Felker (@Solido)

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.8
  image: ^2.1.12
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

