name: flutter_blurhash
description: Compact representation of a placeholder for an image. Encode a blurry image under 30 caracters for instant display like used by Medium
version: 0.1.2
homepage: https://github.com/Solido/Flutter-BlurHash
authors:
  - Robert Felker <flutter@robbieone.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter